name: Docker
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: docker build . -t halfgaar/flashmq
      - run: docker run halfgaar/flashmq /bin/flashmq --version
